name: Java CI/CD with Gradle

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Spring Boot Build
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test
    
    # Docker image Build
    - name: docker image build
      run: docker build -t yubyeongsoo/pet119-spring-staging .

     # DockeHub Login
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Docker Hub push
    - name: docker Hub push
      run: docker push yubyeongsoo/pet119-spring-staging
      
    # GET GitHub IP
    - name: get GitHub IP
      id: ip
      uses: haythem/public-ip@v1.2
      
    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
      
    # Add github ip to AWS
    - name: Add GitHub IP to AWS
      run : |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        
    # AWS EC2 Server Connect & Docker 명령어 실행
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }} 
        port: ${{ secrets.EC2_SSH_PORT }}
        timeout: 60s 
        script: |
           sudo docker stop pet119-spring-staging
           sudo docker rm pet119-spring-staging
           sudo docker rmi $(sudo docker images -q yubyeongsoo/pet119-spring-staging)
           sudo docker pull yubyeongsoo/pet_119_back
           sudo docker run -d -p 8080:8080 --name pet_119_back yubyeongsoo/pet119-spring-staging


    # REMOVE Github IP FROM security group
    - name: Remove IP FROM security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
